apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: api-gateway-secrets
    namespace: videocoach-staging
    labels:
      app: videocoach
      environment: staging
      component: api-gateway
      security-tier: high
    annotations:
      security.videocoach.com/rotation-schedule: "30d"
      security.videocoach.com/last-rotated: "2023-11-01T00:00:00Z"
      security.videocoach.com/owner: "security-team"
  type: Opaque
  data:
    JWT_SECRET: ${base64:jwt-secret-key}
    AUTH0_CLIENT_SECRET: ${base64:auth0-client-secret}
    AUTH0_DOMAIN: ${base64:auth0-domain}
    AUTH0_AUDIENCE: ${base64:auth0-audience}
    AUTH0_CLIENT_ID: ${base64:auth0-client-id}

- apiVersion: v1
  kind: Secret
  metadata:
    name: payment-secrets
    namespace: videocoach-staging
    labels:
      app: videocoach
      environment: staging
      component: payment-service
      security-tier: high
      pci-compliance: required
    annotations:
      security.videocoach.com/rotation-schedule: "90d"
      security.videocoach.com/last-rotated: "2023-11-01T00:00:00Z"
      security.videocoach.com/owner: "finance-team"
  type: Opaque
  data:
    STRIPE_SECRET_KEY: ${base64:stripe-secret-key}
    STRIPE_WEBHOOK_SECRET: ${base64:stripe-webhook-secret}
    STRIPE_ENDPOINT_SECRET: ${base64:stripe-endpoint-secret}

- apiVersion: v1
  kind: Secret
  metadata:
    name: db-secrets
    namespace: videocoach-staging
    labels:
      app: videocoach
      environment: staging
      component: database
      security-tier: high
    annotations:
      security.videocoach.com/rotation-schedule: "60d"
      security.videocoach.com/last-rotated: "2023-11-01T00:00:00Z"
      security.videocoach.com/owner: "db-team"
  type: Opaque
  data:
    POSTGRES_USER: ${base64:postgres-user}
    POSTGRES_PASSWORD: ${base64:postgres-password}
    POSTGRES_DB: ${base64:postgres-db}
    MONGODB_URI: ${base64:mongodb-uri}
    MONGODB_USER: ${base64:mongodb-user}
    MONGODB_PASSWORD: ${base64:mongodb-password}
    REDIS_PASSWORD: ${base64:redis-password}
    REDIS_TLS_CERT: ${base64:redis-tls-cert}

- apiVersion: v1
  kind: Secret
  metadata:
    name: storage-secrets
    namespace: videocoach-staging
    labels:
      app: videocoach
      environment: staging
      component: storage
      security-tier: high
    annotations:
      security.videocoach.com/rotation-schedule: "90d"
      security.videocoach.com/last-rotated: "2023-11-01T00:00:00Z"
      security.videocoach.com/owner: "infrastructure-team"
  type: Opaque
  data:
    AWS_ACCESS_KEY_ID: ${base64:aws-access-key}
    AWS_SECRET_ACCESS_KEY: ${base64:aws-secret-key}
    AWS_REGION: ${base64:aws-region}
    S3_BUCKET_NAME: ${base64:s3-bucket-name}
    CDN_DISTRIBUTION_ID: ${base64:cdn-distribution-id}

- apiVersion: v1
  kind: Secret
  metadata:
    name: video-service-secrets
    namespace: videocoach-staging
    labels:
      app: videocoach
      environment: staging
      component: video-service
      security-tier: high
    annotations:
      security.videocoach.com/rotation-schedule: "60d"
      security.videocoach.com/last-rotated: "2023-11-01T00:00:00Z"
      security.videocoach.com/owner: "video-team"
  type: Opaque
  data:
    ELASTIC_APM_SERVER_URL: ${base64:apm-server-url}
    ELASTIC_APM_SECRET_TOKEN: ${base64:apm-secret-token}
    VIDEO_PROCESSING_KEY: ${base64:video-processing-key}