apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: api-gateway-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: production
      component: api-gateway
    annotations:
      secret.kubernetes.io/rotation-period: "30d"
      secret.kubernetes.io/auto-rotation: "true"
      backup.kubernetes.io/policy: "required"
      encryption.kubernetes.io/kms-key: "aws-kms-key-arn"
  type: Opaque
  data:
    JWT_SECRET: "base64:kms:aws:kms:region:key-id:encrypted-data"
    AUTH0_CLIENT_SECRET: "base64:kms:aws:kms:region:key-id:encrypted-data"
    AUTH0_DOMAIN: "base64:videocoach.auth0.com"
    AUTH0_AUDIENCE: "base64:https://api.videocoach.com"
    AUTH0_ISSUER_URL: "base64:https://videocoach.auth0.com/"
    AUTH0_TOKEN_SIGNING_ALG: "base64:RS256"

- apiVersion: v1
  kind: Secret
  metadata:
    name: payment-secrets
    namespace: videocoach-services
    labels:
      app: videocoach
      environment: production
      component: payment-service
    annotations:
      secret.kubernetes.io/rotation-period: "90d"
      secret.kubernetes.io/auto-rotation: "true"
      encryption.kubernetes.io/kms-key: "aws-kms-key-arn"
      backup.kubernetes.io/policy: "required"
  type: Opaque
  data:
    stripe-api-key: "base64:kms:aws:kms:region:key-id:encrypted-data"
    stripe-webhook-secret: "base64:kms:aws:kms:region:key-id:encrypted-data"
    stripe-endpoint-secret: "base64:kms:aws:kms:region:key-id:encrypted-data"
    stripe-restricted-key: "base64:kms:aws:kms:region:key-id:encrypted-data"

- apiVersion: v1
  kind: Secret
  metadata:
    name: db-secrets
    namespace: videocoach-services
    labels:
      app: videocoach
      environment: production
      component: database
    annotations:
      secret.kubernetes.io/rotation-period: "60d"
      secret.kubernetes.io/auto-rotation: "true"
      backup.kubernetes.io/policy: "required"
      encryption.kubernetes.io/kms-key: "aws-kms-key-arn"
  type: Opaque
  data:
    POSTGRES_USER: "base64:kms:aws:kms:region:key-id:encrypted-data"
    POSTGRES_PASSWORD: "base64:kms:aws:kms:region:key-id:encrypted-data"
    POSTGRES_HOST: "base64:videocoach-db.production.svc.cluster.local"
    POSTGRES_PORT: "base64:5432"
    MONGODB_URI: "base64:mongodb+srv://user:pass@videocoach-mongo.production/"
    MONGODB_USER: "base64:kms:aws:kms:region:key-id:encrypted-data"
    MONGODB_PASSWORD: "base64:kms:aws:kms:region:key-id:encrypted-data"
    REDIS_PASSWORD: "base64:kms:aws:kms:region:key-id:encrypted-data"
    REDIS_HOST: "base64:redis-master.production.svc.cluster.local"
    REDIS_PORT: "base64:6379"

- apiVersion: v1
  kind: Secret
  metadata:
    name: storage-secrets
    namespace: videocoach-services
    labels:
      app: videocoach
      environment: production
      component: storage
    annotations:
      secret.kubernetes.io/rotation-period: "90d"
      secret.kubernetes.io/auto-rotation: "true"
      replication.kubernetes.io/multi-region: "true"
      encryption.kubernetes.io/kms-key: "aws-kms-key-arn"
      backup.kubernetes.io/policy: "required"
  type: Opaque
  data:
    AWS_ACCESS_KEY_ID: "base64:kms:aws:kms:region:key-id:encrypted-data"
    AWS_SECRET_ACCESS_KEY: "base64:kms:aws:kms:region:key-id:encrypted-data"
    AWS_REGION: "base64:us-east-1"
    S3_BUCKET_NAME: "base64:videocoach-prod-videos"
    CDN_DISTRIBUTION_ID: "base64:kms:aws:kms:region:key-id:encrypted-data"
    KMS_KEY_ARN: "base64:arn:aws:kms:region:account:key/key-id"