apiVersion: v1
kind: ConfigMap
metadata:
  name: videocoach-dev-config
  namespace: development
  labels:
    app: videocoach
    environment: development
data:
  # Environment Settings
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  API_VERSION: "v1"

  # API Gateway Configuration
  API_GATEWAY_PORT: "3000"
  API_GATEWAY_HOST: "0.0.0.0"
  CORS_ENABLED: "true"
  CORS_ORIGIN: "http://localhost:3000,https://dev.videocoach.com"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  
  # Rate Limiting Configuration
  RATE_LIMIT_PUBLIC: "100"
  RATE_LIMIT_AUTHENTICATED: "1000"
  RATE_LIMIT_VIDEO_UPLOAD: "10"
  RATE_LIMIT_ANALYTICS: "500"
  RATE_LIMIT_WINDOW: "60"
  RATE_LIMIT_BURST: "1.5"

  # Video Service Configuration
  VIDEO_SERVICE_PORT: "8000"
  VIDEO_SERVICE_HOST: "0.0.0.0"
  VIDEO_PROCESSING_TIMEOUT: "60"
  VIDEO_PROCESSING_THREADS: "4"
  MAX_VIDEO_SIZE_MB: "500"
  SUPPORTED_VIDEO_FORMATS: ".mp4,.mov,.avi,.mkv,.webm"
  VIDEO_QUALITY_PROFILES: "HD:1080p:8000k,SD:720p:4000k,MOBILE:480p:2000k"
  VIDEO_CODEC: "h264"
  AUDIO_CODEC: "aac"
  THUMBNAIL_GENERATION: "true"
  THUMBNAIL_INTERVALS: "0,25,50,75"

  # Service Ports & Hosts
  PAYMENT_SERVICE_PORT: "3003"
  PAYMENT_SERVICE_HOST: "0.0.0.0"
  PAYMENT_API_PREFIX: "/api/v1/payments"
  CHAT_SERVICE_PORT: "3002"
  CHAT_SERVICE_HOST: "0.0.0.0"
  CHAT_WEBSOCKET_PATH: "/ws"
  COACH_SERVICE_PORT: "3004"
  COACH_SERVICE_HOST: "0.0.0.0"
  USER_SERVICE_PORT: "3001"
  USER_SERVICE_HOST: "0.0.0.0"

  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_MAX_CONNECTIONS: "50"

  # Monitoring Configuration
  PROMETHEUS_PORT: "9090"
  METRICS_ENABLED: "true"
  METRICS_INTERVAL: "15"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  TRACING_ENABLED: "true"
  JAEGER_AGENT_HOST: "jaeger"
  JAEGER_AGENT_PORT: "6831"

  # Storage Configuration
  S3_PREFIX: "videos/"
  S3_BUCKET_REGION: "us-east-1"
  CDN_BASE_URL: "https://dev-cdn.videocoach.com"
  CDN_CACHE_DURATION: "3600"

  # Database Configuration
  DB_NAME: "videocoach_dev"
  DB_MAX_CONNECTIONS: "20"
  DB_IDLE_TIMEOUT: "30000"