apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: api-gateway-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: development
      component: api-gateway
    annotations:
      kubernetes.io/rotate-after: "720h"
      videocoach.io/secret-category: "auth"
      encryption.videocoach.io/kms-key: "arn:aws:kms:us-east-1:videocoach:key/api-gateway"
  type: Opaque
  stringData:
    JWT_SECRET: "${JWT_SECRET}"
    AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
    AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
    AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
    AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
    AUTH0_MFA_ENABLED: "true"
    AUTH0_MFA_FACTORS: "otp,push,webauthn"
    KEY_ROTATION_INTERVAL: "86400"

- apiVersion: v1
  kind: Secret
  metadata:
    name: video-service-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: development
      component: video-service
    annotations:
      kubernetes.io/rotate-after: "720h"
      videocoach.io/secret-category: "storage"
      encryption.videocoach.io/kms-key: "arn:aws:kms:us-east-1:videocoach:key/video-service"
  type: Opaque
  stringData:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
    REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ELASTIC_APM_SERVER_URL: "https://apm.dev.videocoach.com"
    ELASTIC_APM_SECRET_TOKEN: "${ELASTIC_APM_SECRET_TOKEN}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: payment-service-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: development
      component: payment-service
    annotations:
      kubernetes.io/rotate-after: "720h"
      videocoach.io/secret-category: "payment"
      encryption.videocoach.io/kms-key: "arn:aws:kms:us-east-1:videocoach:key/payment-service"
  type: Opaque
  stringData:
    STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
    STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
    STRIPE_ENDPOINT_SECRET: "${STRIPE_ENDPOINT_SECRET}"
    MONGODB_URI: "mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@dev-cluster.videocoach.com/videocoach_payments?retryWrites=true&w=majority"
    REDIS_PASSWORD: "${REDIS_PASSWORD}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: db-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: development
      component: database
    annotations:
      kubernetes.io/rotate-after: "720h"
      videocoach.io/secret-category: "database"
      encryption.videocoach.io/kms-key: "arn:aws:kms:us-east-1:videocoach:key/database"
  type: Opaque
  stringData:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    POSTGRES_DB: "videocoach_dev"
    MONGODB_URI: "mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@dev-cluster.videocoach.com/videocoach?retryWrites=true&w=majority"
    MONGODB_REPLICA_SET: "dev-replica-set"
    REDIS_PASSWORD: "${REDIS_PASSWORD}"
    REDIS_TLS_ENABLED: "true"

- apiVersion: v1
  kind: Secret
  metadata:
    name: monitoring-secrets
    namespace: videocoach-system
    labels:
      app: videocoach
      environment: development
      component: monitoring
    annotations:
      kubernetes.io/rotate-after: "720h"
      videocoach.io/secret-category: "monitoring"
      encryption.videocoach.io/kms-key: "arn:aws:kms:us-east-1:videocoach:key/monitoring"
  type: Opaque
  stringData:
    PROMETHEUS_BASIC_AUTH_USER: "${PROMETHEUS_USER}"
    PROMETHEUS_BASIC_AUTH_PASS: "${PROMETHEUS_PASSWORD}"
    GRAFANA_ADMIN_USER: "${GRAFANA_ADMIN}"
    GRAFANA_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    ALERT_MANAGER_CONFIG: "${ALERT_MANAGER_CONFIG}"