apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: videocoach-system
    labels:
      name: videocoach-system
      environment: production
      app.kubernetes.io/name: videocoach
      app.kubernetes.io/part-of: video-coaching-platform
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/created-by: infrastructure-team
    annotations:
      description: Main namespace for Video Coaching Platform components
      monitoring.enabled: "true"
      logging.enabled: "true"
      security.network.k8s.io/isolation: strict
      backup.velero.io/schedule: daily
      quota.management.k8s.io/ignore-pod-limits: "false"

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: videocoach-quota
    namespace: videocoach-system
    labels:
      app.kubernetes.io/name: videocoach
      app.kubernetes.io/part-of: video-coaching-platform
  spec:
    hard:
      requests.cpu: "20"
      requests.memory: 40Gi
      limits.cpu: "40"
      limits.memory: 80Gi
      pods: "100"
      services: "50"
      persistentvolumeclaims: "50"
      secrets: "100"
      configmaps: "100"
      services.nodeports: "10"
      services.loadbalancers: "5"
      requests.storage: 500Gi

- apiVersion: v1
  kind: LimitRange
  metadata:
    name: videocoach-limits
    namespace: videocoach-system
    labels:
      app.kubernetes.io/name: videocoach
      app.kubernetes.io/part-of: video-coaching-platform
  spec:
    limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 100m
        memory: 128Mi