apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-gateway
    namespace: videocoach-system
    labels:
      app: api-gateway
      component: gateway
      part-of: video-coaching-platform
      version: 1.0.0
      managed-by: kubectl
      environment: production
    annotations:
      kubernetes.io/description: "API Gateway for Video Coaching Platform"
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000"
      prometheus.io/path: "/metrics"
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: api-gateway
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: api-gateway
          security-tier: gateway
          version: 1.0.0
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3000"
          prometheus.io/path: "/metrics"
          checksum/config: "${CONFIG_CHECKSUM}"
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 2000
        containers:
        - name: api-gateway
          image: videocoach/api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
          env:
          - name: NODE_ENV
            value: "production"
          - name: API_GATEWAY_PORT
            value: "3000"
          - name: LOG_LEVEL
            value: "info"
          envFrom:
          - configMapRef:
              name: api-gateway-config
          - secretRef:
              name: api-gateway-secrets
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL

- apiVersion: v1
  kind: Service
  metadata:
    name: api-gateway
    namespace: videocoach-system
    labels:
      app: api-gateway
      component: gateway
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
      app: api-gateway
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800

- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: api-gateway-hpa
    namespace: videocoach-system
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: api-gateway
    minReplicas: 3
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 120